#!/usr/bin/env sh
VM_NAME=boot2docker-vm
VBM=VBoxManage

DOCKER_PORT=4243
SSH_HOST_PORT=2022

VM_DISK=./boot2docker.vmdk
VM_DISK_SIZE=40000

VM_MEM=1024

BOOT2DOCKER_ISO=./boot2docker.iso

test -f $HOME/.boot2docker/profile && . $HOME/.boot2docker/profile

get_latest_release_name() {
    local LRN
    LRN=$(curl 'https://api.github.com/repos/steeve/boot2docker/releases' 2>/dev/null|grep -o -m 1 -e "\"tag_name\":[[:space:]]*\"[a-z0-9.]*\""|head -1|cut -d: -f2|tr -d ' "')
    if [ -z "$LRN" ]; then
        echo "ERROR"
    else
        echo "$LRN"
    fi
}

download_latest() {
    LATEST_RELEASE=$(get_latest_release_name)
    if [ ! "$LATEST_RELEASE" = "ERROR" ]; then
        log "Latest version is $LATEST_RELEASE, downloading..."
        mkdir -p "${BOOT2DOCKER_ISO%/*}"
        curl -L -o "$BOOT2DOCKER_ISO" "https://github.com/steeve/boot2docker/releases/download/$LATEST_RELEASE/boot2docker.iso"
        log "Done"
    else
        log "Could not get lastest release name! Cannot download boot2docker.iso."
    fi
}

log() {
    echo "[`date +"%Y-%m-%d %H:%M:%S"`] ${*}"
}

init() {

    if `$VBM showvminfo $VM_NAME > /dev/null 2>&1`; then
	    echo "$VM_NAME Virtual Box vm already exists"
	    exit 1
    fi

    VM_OSTYPE=Linux26_64
    VM_NIC=virtio
    unamestr=`uname`
    case $unamestr in
        Linux) VM_CPUS=`nproc`;;
        Darwin) VM_CPUS=`sysctl -n hw.physicalcpu`;;
        *) echo "$unamestr not yet supported - please raise an issue" ; exit 1
    esac

    if `nc -z -w2 localhost $DOCKER_PORT > /dev/null` ; then
        log "DOCKER_PORT=$DOCKER_PORT on localhost is used by an other process! Change the port to a free port."
        exit 1
    fi

    if `nc -z -w2 localhost $SSH_HOST_PORT > /dev/null` ; then
        log "SSH_HOST_PORT=$SSH_HOST_PORT on localhost is used by an other process! Change the port to a free port."
        exit 1
    fi

    log "Creating VM $VM_NAME"
    $VBM createvm --name $VM_NAME --register

    log "Setting VM settings"
    TXUX_SUPPORT=""
    if $($VBM modifyvm|grep -q "\-\-vtxux"); then
        TXUX_SUPPORT="--vtxux on"
    fi

    if ! $VBM modifyvm $VM_NAME \
        --ostype $VM_OSTYPE \
        --cpus $VM_CPUS \
        --memory $VM_MEM \
        --rtcuseutc on \
        --acpi on \
        --ioapic on \
        --hpet on \
        --hwvirtex on \
        --vtxvpid on \
        $TXUX_SUPPORT \
        --largepages on \
        --nestedpaging on \
        --firmware bios \
        --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled \
        --boot1 dvd; then
      echo "An error occured, upgrade VirtualBox or try to disable some options"
      delete
      exit 1
    fi

    log "Setting VM networking"
    $VBM modifyvm $VM_NAME \
        --nic1 nat \
        --nictype1 $VM_NIC \
        --cableconnected1 on
    if `$VBM showvminfo $VM_NAME | grep Rule | grep ssh > /dev/null`; then
	    $VBM modifyvm $VM_NAME \
        	--natpf1 delete "ssh"
    fi
    if `$VBM showvminfo $VM_NAME | grep Rule | grep docker > /dev/null`; then
	    $VBM modifyvm $VM_NAME \
        	--natpf1 delete "docker"
    fi
    $VBM modifyvm $VM_NAME \
        --nic2 hostonly \
        --hostonlyadapter2 vboxnet0 \
        --nictype2 $VM_NIC \
        --cableconnected2 on
    $VBM modifyvm $VM_NAME \
        --natpf1 "ssh,tcp,127.0.0.1,$SSH_HOST_PORT,,22" \
        --natpf1 "docker,tcp,127.0.0.1,$DOCKER_PORT,,4243"

    if [ ! -e $BOOT2DOCKER_ISO ]; then
        log "boot2docker.iso not found."
        download_latest
    fi

    log "Setting VM disks"
    if `$VBM showvminfo $VM_NAME | grep SATA > /dev/null`; then
        $VBM storagectl $VM_NAME --name "SATA" --remove
    fi

    if [ ! -e $VM_DISK ]; then
        log "Creating $VM_DISK_SIZE Meg hard drive..."
        # closemedium may complain when not needed
        $VBM closemedium disk $VM_DISK > /dev/null 2>&1
        ## make a simple text file, and use that as the flag to say 'format me'
        $VBM createhd --format VMDK --filename $VM_DISK --size $VM_DISK_SIZE

        echo "boot2docker, please format-me" | cat - /dev/zero | head -c 5242880 > format-flag.txt # 5M
        $VBM convertfromraw format-flag.txt format-flag.vmdk --format VMDK
        $VBM clonehd format-flag.vmdk $VM_DISK --existing
        $VBM closemedium disk format-flag.vmdk > /dev/null 2>&1 && rm format-flag.txt format-flag.vmdk
    fi

    $VBM storagectl $VM_NAME --name "SATA" --add sata --hostiocache on
    $VBM storageattach $VM_NAME --storagectl "SATA" --port 0 --device 0 --type dvddrive --medium $BOOT2DOCKER_ISO
    $VBM storageattach $VM_NAME --storagectl "SATA" --port 1 --device 0 --type hdd --medium $VM_DISK

    log "Done."
    log "You can now type boot2docker up and wait for the VM to start."
}

do_ssh() {
    is_installed || status
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $SSH_HOST_PORT docker@localhost $*
}

start() {
    is_installed || status
    if ! is_running; then
        if is_paused; then
            log "Resuming $VM_NAME"
            $VBM controlvm $VM_NAME resume > /dev/null
            wait_vm
            log "Resumed."
        else
            log "Starting $VM_NAME..."
            $VBM startvm $VM_NAME --type headless > /dev/null &
            wait_vm
            log "Started."
        fi
    else
        log "$VM_NAME is already running."
    fi
}

wait_vm() {
    while ! echo "ping" | nc localhost $SSH_HOST_PORT > /dev/null 2>&1; do
        sleep 1
    done
}

pause() {
    is_installed || status
    if is_running; then
        log "Pausing $VM_NAME..."
        $VBM controlvm $VM_NAME pause > /dev/null
    else
        log "$VM_NAME is not running."
    fi
}

stop() {
    is_installed || status
    if is_running; then
        log "Shutting down $VM_NAME..."
        $VBM controlvm $VM_NAME acpipowerbutton > /dev/null
        while is_running; do
            sleep 1
        done
    else
        log "$VM_NAME is not running."
    fi
}

restart() {
    is_installed || status
    if is_running; then
        stop && sleep 1 && start
    else
        start
    fi
}

info() {
    if is_installed; then
        $VBM showvminfo $VM_NAME
    else
        echo "$VM_NAME does not exist."
    fi
}

is_installed() {
    $VBM list vms | grep "$VM_NAME" > /dev/null
}

is_running() {
    info | grep "State:\s\+running" > /dev/null
}

is_paused() {
    info | grep "State:\s\+paused" > /dev/null
}

is_stopped() {
    info | grep "State:\s\+powered off" > /dev/null
}

is_aborted() {
    info | grep "State:\s\+aborted" > /dev/null
}

status() {
    if is_running; then
        log "$VM_NAME is running."
        exit 0
    elif is_paused; then
        log "$VM_NAME is suspended."
        exit 1
    elif is_stopped; then
        log "$VM_NAME is stopped."
        exit 1
    else
        log "$VM_NAME does not exist."
        exit 1
    fi
}

delete() {
    if [ ! is_stopped ] || [ ! is_aborted ]; then
        log "$VM_NAME needs to be stopped to delete it."
        exit 1
    fi
    $VBM unregistervm --delete $VM_NAME
}

docker_cmd() {
    echo "CMD: $@"
    DCMD=$@
    if [[ $DCMD =~ [-]name[[:space:]]([a-zA-Z0-9_-]+) ]]; then
        CNAME=${BASH_REMATCH[1]}
        # echo "name: $CNAME"
    fi

    if [[ -n "$CNAME" ]] && [[ $DCMD =~ [-]v[[:space:]]([^:\ ]*):([^:\ ]*)(:ro|:rw){0,1} ]]; then
        MHD_ORIG=${BASH_REMATCH}
        MHD_HD_SHARE=$(cd ${BASH_REMATCH[1]}; pwd)
        MHD_HD_MOUNT=$(md5 -q -s "$MHD_HD_SHARE")
        MHD_HD_MOUNT="/var/lib/docker/share/$MHD_HD_MOUNT"
        MHD_OPTION="-v $MHD_HD_MOUNT:${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
        CUGID=$(id)
        if [[ $CUGID =~ uid\=([0-9]+)\(.*\)[[:space:]]gid\=([0-9]+) ]]; then
            MUID=${BASH_REMATCH[1]}
            MGID=${BASH_REMATCH[2]}
        else
            log "Could not get User ID"
            exit 1
        fi
        log "nfs /etc/exports add $MHD_HD_SHARE"

        SHARE_ESCAPED="${MHD_HD_SHARE//\//\/}"
        MHD_HD_EXPORT_CMD="sudo sed -i.bak '/\"$SHARE_ESCAPED\"/d' /etc/exports; sudo echo \"\\\"$MHD_HD_SHARE\\\" -network 192.168.56.0 -mask 255.255.255.0 -alldirs -mapall=$MUID:$MGID\" >> /etc/exports; sudo nfsd update"
        unamestr=`uname`

        if [[ ! `sudo -v` ]] && [[ "$unamestr" == "Darwin" ]]; then
            MHD_HD_EXPORT_CMD_TMP=$(mktemp -t b2d)
            echo $MHD_HD_EXPORT_CMD > $MHD_HD_EXPORT_CMD_TMP
            osascript -e "do shell script \"sh $MHD_HD_EXPORT_CMD_TMP\" with administrator privileges"
            rm $MHD_HD_EXPORT_CMD_TMP
        else
            $MHD_HD_EXPORT_CMD
        fi
        log "mount $MHD_HD_SHARE to $MHD_HD_MOUNT"
        # sudo /bin/bash -c echo "\"$MHD_HD_SHARE\" -network 192.168.56.0 -mask 255.255.255.0 -alldirs -mapall=502:20" >> /etc/exports
        do_ssh "sudo mkdir -p $MHD_HD_MOUNT; sudo /usr/local/etc/init.d/nfs-client start; sudo mount 192.168.56.1:$MHD_HD_SHARE $MHD_HD_MOUNT"
        DCMD="${DCMD/$MHD_ORIG/$MHD_OPTION}"
    fi

    if [[ -n "$CNAME" ]] && [[ $DCMD =~ -p[[:space:]]([a-zA-Z0-9_\\-\\.]*):*([0-9]*):*([0-9]*)(/udp){0,1} ]]; then
        # echo $BASH_REMATCH      
        # echo ${BASH_REMATCH[1]} 
        # echo ${BASH_REMATCH[2]} 
        # echo ${BASH_REMATCH[3]} 
        # echo ${BASH_REMATCH[4]}
        PP0=$BASH_REMATCH
        PP1=${BASH_REMATCH[1]}
        PP2=${BASH_REMATCH[2]}
        PP3=${BASH_REMATCH[3]}
        PP4=${BASH_REMATCH[4]}
        if [[ $PP1 =~ [a-zA-Z0-9](-*[a-zA-Z0-9]+)*(\.[a-zA-Z0-9](-*[a-zA-Z0-9]+)*)+ ]]; then
            PB_HOST_IF=$PP1
            if [ "" == "$PP3" ]; then
                PB_CPORT=$PP2
            else
                PB_CPORT=$PP3
                PB_HPORT=$PP2
            fi
        else
            # echo "no IP"
            if [ "" == "$PP2" ]; then
                PB_CPORT=$PP1
            else
                PB_CPORT=$PP2
                PB_HPORT=$PP1
            fi
        fi
        PB_OPTION="-p 0.0.0.0::$PB_CPORT"
        if [ "" == "$PP4" ]; then
            PB_TYP=tcp
        else
            PB_TYP=udp
        fi
        # echo "$PB_HOST_IF:$PB_HPORT:$PB_CPORT"
        # echo "$PB_OPTION"
        DCMD="${DCMD/$PP0/$PB_OPTION}"
        echo "docker $DCMD"

        docker $DCMD
        # echo "docker port $CNAME $PB_CPORT"
        PBDYN=$(docker port $CNAME $PB_CPORT)
        # echo $PBDYN
        if [[ $PBDYN =~ ([a-zA-Z0-9_\\-\\.]*):*([0-9]*) ]]; then
            PB_VM_IF=${BASH_REMATCH[1]}
            # PB_VM_IF=""
            PB_DPORT=${BASH_REMATCH[2]}
            if [ "" == "$PB_HOST_IF" ]; then
                PB_HOST_IF="127.0.0.1"
            fi
            if [ "" == "$PB_HPORT" ]; then
                PB_HPORT=$PB_DPORT
            fi
            CFWPORTS=""
            CFWPORTS="$CFWPORTS natpf1 zfp$PB_HPORT,$PB_TYP,$PB_HOST_IF,$PB_HPORT,$PB_VM_IF,$PB_DPORT"
            #echo $CFWPORTS
            echo "$VBM controlvm $VM_NAME natpf1 delete zfp$PB_HPORT"
            echo "$VBM controlvm $VM_NAME $CFWPORTS"
            $VBM controlvm $VM_NAME setlinkstate1 off
            $VBM controlvm $VM_NAME natpf1 delete zfp$PB_HPORT  > /dev/null 2>&1
            $VBM controlvm $VM_NAME $CFWPORTS
            $VBM controlvm $VM_NAME setlinkstate1 on
        fi
    else
        echo "missed"
        docker $1
    fi
}

case $1 in
    init | setup) init;;
    start | up) start;;
    pause | suspend) pause;;
    stop | halt | down) stop;;
    restart) restart;;
    status) status;;
    info) info;;
    delete) delete;;
    ssh) shift; do_ssh "$@";;
    download) download_latest;;
    cmd) shift; docker_cmd "$@";;
    *) echo "Usage $0 {init|start|up|pause|stop|restart|status|info|delete|ssh|download|cmd}"; exit 1
esac