FROM dockercore/iso

RUN { \
		echo 'VARIANT="VirtualBox"'; \
		echo 'VARIANT_ID=virtualbox'; \
	} >> /etc/os-release

RUN sed -i 's/ main$/ main contrib/' /etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends \
		$(dpkg-query --show --showformat='${Package}\n' | awk '/^linux-image-[0-9]/ { gsub(/-image-/, "-headers-"); print }') \
		\
		virtualbox-guest-dkms \
		virtualbox-guest-utils \
	&& rm -rf /var/lib/apt/lists/*
