FROM dockercore/iso

RUN { \
		echo 'VARIANT="VMware"'; \
		echo 'VARIANT_ID=vmware'; \
	} >> /etc/os-release

RUN apt-get update && apt-get install -y open-vm-tools && rm -rf /var/lib/apt/lists/*

# simple, dirty fix for being able to mount inside /Users and have that work
RUN mkdir -p /Users && chgrp docker /Users && chmod g+rwx /Users
# ... and /c/Users for Windows
RUN mkdir -p /c/Users && chgrp -R docker /c && chmod g+rwx /c
