#!/bin/sh
# docker daemon start script
[ $(id -u) = 0 ] || { echo "must be root" ; exit 1; }

start(){
    # TODO move this logfile out of /var/lib/docker
    # Capture docker0 IP address, in the extremely unlikely event it ever changes
    DOCKER_ADDR = `/sbin/ifconfig docker0 | grep 'inet addr:' | cut -d: -f2| cut -d' ' -f1`
    # Allow dockerd access from the container network (so that we can use shipyard, etc.)
    /usr/local/bin/docker -d -H tcp://$DOCKER_ADDR:4243 -H unix:///var/run/docker.sock > /var/lib/docker/docker.log 2>&1 &
}

stop(){
   kill $(cat /var/run/docker.pid)
}

restart(){
   if check; then
      stop && sleep 1 && start
   else
      start
   fi
}

check(){
  [ -f /var/run/docker.pid ] && ps $(cat /var/run/docker.pid) > /dev/null 2>&1
}

status(){
  if check; then
    echo "Docker daemon is running"
    exit 0
  else
    echo "Docker daemon is not running"
    exit 1
  fi
}

case $1 in
   start) start;;
   stop) stop;;
   restart) restart;;
   status) status;;
   *) echo "Usage $0 {start|stop|restart|status}"; exit 1
esac
