#!/bin/sh

if [ -n "$NTP_SERVER" ]; then
    # Wait on the network
    while ! ping -c 1 $NTP_SERVER &> /dev/null; do
        sleep 1
    done

    # First, set the system time to the NTP server
    echo "running ntpclient -s -g 1000000 -h $NTP_SERVER" > /var/lib/boot2docker/log/ntpclient.log 2>&1
    /usr/local/bin/ntpclient -s -g 1000000 -h $NTP_SERVER >> /var/lib/boot2docker/log/ntpclient.log 2>&1
    # Then lock it
    echo "running ntpclient -l -q 200 -i 30 -h $NTP_SERVER in the background" >> /var/lib/boot2docker/log/ntpclient.log 2>&1
    /usr/local/bin/ntpclient -l -q 200 -i 30 -h $NTP_SERVER >> /var/lib/boot2docker/log/ntpclient.log 2>&1 &
else
    echo "Skipping ntpclient" > /var/lib/boot2docker/log/ntpclient.log 2>&1
fi
