#!/bin/sh

# Creates mountpoint for Shared Folders
if [ ! -d /mnt/hgfs ]; then
	mkdir -p /mnt/hgfs
	# load shared folders kernel module
	modprobe vmhgfs
	# try to mount the root shared folder, this command can fail
	# if shared folders are disabled on the host, vmtoolsd will take care of the mount
	# if they are enabled while the machine is running.
	mount -t vmhgfs .host:/ /mnt/hgfs
fi

/usr/local/bin/vmtoolsd --background /var/run/vmtoolsd.pid
